workflows:
  ios_release:
    name: iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m1
    working_directory: .
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter --version
      - flutter pub get
      - flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: api_key
        key_id: $APP_STORE_KEY_ID
        issuer_id: $APP_STORE_ISSUER_ID
        submit_to_testflight: true
