workflows:
  ios_release:
    name: iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m1
    working_directory: .
    integrations:
      app_store_connect: Codemagic API Key   # <-- must match the name you used in Codemagic
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter --version
      - flutter clean
      - flutter pub get
      - flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
