# Codemagic configuration — updated to surface first error lines and build iOS (device only, no codesign)
# Notes:
# - Uses a verbose build script that cleans Pods/DerivedData and captures flutter/xcode logs.
# - Produces flutter_verbose.log as an artifact for quick triage.
# - Targets iOS device builds without code signing.
# - Keeps caches for faster subsequent builds.

workflows:
  name:
    name: iOS Release (no codesign) — verbose
    instance_type: mac_mini_m2

    environment:
      flutter: stable        # or pin to a specific version if you prefer
      xcode: "15.4"          # match your local Xcode if needed
      cocoapods: default
      vars:
        LC_ALL: en_US.UTF-8
        LANG: en_US.UTF-8

    scripts:
      - name: Flutter pub get
        script: |
          flutter pub get

      - name: Build iOS (device only, no codesign, verbose)
        script: |
          set -euo pipefail

          # Show tool versions
          flutter --version
          dart --version
          xcodebuild -version
          pod --version || true

          # Doctor is informative but non-blocking
          flutter doctor -v || true

          # Clean caches that commonly cause phantom exits
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock ~/Library/Developer/Xcode/DerivedData
          cd ios && pod repo update && cd ..

          # Ultra-verbose Flutter build and capture logs
          export FLUTTER_VERBOSE=true
          export NSUnbufferedIO=YES

          # If you use flavors, append: --flavor <yourFlavor>
          flutter build ios --release --no-codesign -v             --build-name=$CM_BUILD_NAME --build-number=$CM_BUILD_NUMBER 2>&1 | tee flutter_verbose.log

          # If Flutter punts to xcodebuild, try to tail its last lines for context
          if grep -m1 -E "Xcode build done|Failed to build iOS app" flutter_verbose.log; then
            XCODE_LOG=$(grep -m1 -oE "/.*xcodebuild.*\.log" flutter_verbose.log || true)
            if [ -n "$XCODE_LOG" ] && [ -f "$XCODE_LOG" ]; then
              echo "=== TAILING xcodebuild log (last 400 lines) ==="
              tail -n 400 "$XCODE_LOG"
            fi
          fi

          # Highlight the first error-like line so we can fix root cause quickly
          echo "=== FIRST ERROR-LIKE LINE ==="
          grep -n -E "❌|error: |fatal error: |Undefined symbols|ld: warning|No such module|Command CompileSwift failed|Command Ld failed" flutter_verbose.log | head -n 1 || true

    artifacts:
      - build/ios/**/*.xcarchive
      - build/ios/iphoneos/*.app
      - flutter_verbose.log

    cache:
      cache_paths:
        - $HOME/Library/Caches/CocoaPods
        - ios/Pods
        - ~/.pub-cache

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "*"
          include: true
          source: true
