workflows:
  ios_release:
    name: iOS Release
    instance_type: mac_mini_m1
    max_build_duration: 60
    working_directory: .
    integrations:
      app_store_connect: Codemagic API Key   # must match your integration name
    environment:
      flutter: stable
      xcode: latest
    scripts:
  - name: Flutter version & clean
    script: |
      flutter --version
      flutter clean
      flutter pub get
  - name: Set up signing (fetch & install profiles/certs)
    script: |
      keychain initialize
      app-store-connect fetch-signing-files \
        "com.zeusconcrete.pileestimator" \
        --type IOS_APP_STORE \
        --create
      keychain add-certificates
      xcode-project use-profiles
  - name: Build iOS and create IPA
    script: |
      flutter build ios --release --no-codesign
      xcode-project build-ipa

    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
