workflows:
  ios_release:
    name: iOS Release
    instance_type: mac_mini_m1
    max_build_duration: 60
    working_directory: .
    integrations:
      app_store_connect: Codemagic API Key
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Flutter prep
        script: |
          flutter --version
          flutter clean
          flutter pub get
      - name: Install uploaded signing identities
        script: |
          # Installs your uploaded *.p12 certificate into a temporary keychain
          keychain initialize
          keychain add-certificates
          # Installs your uploaded *.mobileprovision to the expected location
          xcode-project use-profiles
      - name: Build IPA (codesigned)
        script: |
          # Build without Xcode signing first
          flutter build ios --release --no-codesign
          # Then archive & sign using the installed profile/certificate
          xcode-project build-ipa --workspace "ios/Runner.xcworkspace" --scheme "Runner"
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
