workflows:
  ios_unsigned:
    name: iOS Unsigned Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    working_directory: .
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Prep (clean & pub get)
        script: |
          set -e
          flutter clean
          flutter pub get
      - name: CocoaPods repo update & install
        script: |
          set -e
          cd ios
          rm -rf Pods Podfile.lock
          pod repo update
          pod install
          cd ..
      - name: Build iOS (no codesign)
        script: |
          set -e
          flutter build ios --release --no-codesign
      - name: Package .app into unsigned IPA
        script: |
          set -ex
          echo "Searching for Runner.app under build/* ..."
          APP_PATH=$(find build -type d -name "Runner.app" | head -n 1 || true)
          if [ -z "$APP_PATH" ]; then
            echo "Runner.app not found. Aborting."
            find build -maxdepth 4 -type d | sed 's/^/FOUND DIR: /'
            exit 1
          fi
          echo "Found app at: $APP_PATH"
          WORKDIR=$(pwd)
          mkdir -p artifacts
          cd "$(dirname "$APP_PATH")"
          rm -rf Payload
          mkdir Payload
          cp -R "Runner.app" Payload/
          zip -r "$WORKDIR/artifacts/Runner-unsigned.ipa" Payload
          ls -l "$WORKDIR/artifacts"
    artifacts:
      - artifacts/*.ipa
