workflows:
  ios_unsigned:
    name: iOS Unsigned Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    working_directory: .
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Prep
        script: |
          flutter clean
          flutter pub get
      - name: Build unsigned IPA
        script: |
          flutter build ipa --release --no-codesign
          mkdir -p build/ios/ipa
          cp -r build/ios/ipa/* build/ios/ipa/ || true
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/
